SOURCES = main.c

APPMOD = PD6_Gateway

USE_ADDRESSING = y

PROJDIR = $(CURDIR)
ifndef MOSROOT
  MOSROOT = /workspaces/MansOS
endif

# Include the main makefile
include ${MOSROOT}/mos/make/Makefile
